services:
  - type: worker
    name: bot-alertas-viagem
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHANNEL_ID
        sync: false
      - key: TELEGRAM_PREMIUM_CHANNEL_ID
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
